-- 1) Tabela de configuracoes runtime
create table if not exists public.bot_runtime_configs (
  id bigint generated by default as identity primary key,
  profile text not null unique,
  env_config jsonb not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bot_runtime_configs_active
  on public.bot_runtime_configs (is_active, updated_at desc);

-- 2) Trigger para updated_at
create or replace function public.set_updated_at_bot_runtime_configs()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_bot_runtime_configs on public.bot_runtime_configs;
create trigger trg_set_updated_at_bot_runtime_configs
before update on public.bot_runtime_configs
for each row execute function public.set_updated_at_bot_runtime_configs();

-- 3) Registro de configuracao (profile=production)
insert into public.bot_runtime_configs (profile, env_config, is_active)
values (
  'production',
  $json$
  {
    "API_KEY": "bdb29a91224172614611c41f27962b9896f5474745136f5464d4d8a2a788838e",
    "API_SECRET": "e14075f110222ae15a5f73bdd427246ea5096dfd48a89f1c6d089b2c66aaf98b",
    "SIMULATE": false,
    "USE_CASH_MANAGEMENT": true,
    "PAIR": "BTC-BRL",
    "CYCLE_SEC": 30,
    "SPREAD_PCT": 0.008,
    "MIN_SPREAD_PCT": 0.005,
    "MAX_SPREAD_PCT": 0.008,
    "ORDER_SIZE": 0.00005,
    "MIN_ORDER_SIZE": 0.00005,
    "MAX_ORDER_SIZE": 0.0002,
    "MAX_POSITION": 0.001,
    "INVENTORY_THRESHOLD": 0.0001,
    "BIAS_FACTOR": 0.0003,
    "STOP_LOSS_PCT": 0.025,
    "TAKE_PROFIT_PCT": 0.040,
    "PRICE_DRIFT_PCT": 0.0001,
    "MAX_VOLATILITY_PCT": 5.0,
    "VOL_LIMIT_PCT": 4.0,
    "MAX_ORDER_AGE": 86400,
    "MIN_REPRICE_AGE_SEC": 86400,
    "HISTORICAL_FILLS_WINDOW": 50,
    "SELL_FIRST": true,
    "RECENT_WEIGHT_FACTOR": 0.9,
    "ALERT_PNL_THRESHOLD": -5,
    "ALERT_ROI_THRESHOLD": -5,
    "MIN_VOLUME": 0.00003,
    "DEBUG": true,
    "EXTERNAL_TREND_TIGHTEN_MAX": 0.35,
    "EXTERNAL_TREND_WIDEN_MAX": 0.20,
    "EXTERNAL_TREND_WEIGHT_COINGECKO": 0.7,
    "EXTERNAL_TREND_WEIGHT_COINBASE": 0.7,
    "EXTERNAL_TREND_WEIGHT_KRAKEN": 0.7,
    "EXTERNAL_TREND_DIVERGENCE_CONF": 0.6,
    "EXTERNAL_TREND_VOLATILITY_DAMP": 0.5,
    "MAX_CONCURRENT_PAIRS": 10,
    "MIN_FILL_RATE_FOR_NEW": 30,
    "PAIRS_THROTTLE_CYCLES": 5
  }
  $json$::jsonb,
  true
)
on conflict (profile) do update
set env_config = excluded.env_config,
    is_active = excluded.is_active,
    updated_at = now();
