create table if not exists public.external_trend_history (
  id bigint generated by default as identity primary key,
  trend text not null default 'neutral',
  score numeric not null default 0,
  confidence numeric not null default 0,
  sources jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  "timestamp" bigint not null
);

create index if not exists idx_external_trend_timestamp
  on public.external_trend_history using btree ("timestamp" desc);
