create table if not exists public.bot_contributions (
  id bigint generated by default as identity primary key,
  amount numeric not null,
  type text not null check (type in ('deposit', 'withdraw')),
  note text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_bot_contributions_created_at
  on public.bot_contributions using btree (created_at asc);

create table if not exists public.bot_initial_balances (
  id bigint generated by default as identity primary key,
  profile text not null unique,
  brl numeric not null,
  btc numeric not null,
  total numeric not null,
  captured_at timestamptz not null default now(),
  captured_at_cycle bigint null,
  updated_at timestamptz not null default now()
);

create table if not exists public.bot_momentum_cache (
  id bigint generated by default as identity primary key,
  profile text not null unique,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at_bot_state()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_bot_initial_balances on public.bot_initial_balances;
create trigger trg_set_updated_at_bot_initial_balances
before update on public.bot_initial_balances
for each row execute function public.set_updated_at_bot_state();

drop trigger if exists trg_set_updated_at_bot_momentum_cache on public.bot_momentum_cache;
create trigger trg_set_updated_at_bot_momentum_cache
before update on public.bot_momentum_cache
for each row execute function public.set_updated_at_bot_state();
